import { useEffect, useMemo, useState } from "react";
import { io, type Socket } from "socket.io-client";
import QRCode from "qrcode";

const api=import.meta.env.VITE_API_URL??"http://localhost:3001";
type Player={id:string;nickname:string;score:number;connected:boolean;role:"HOST"|"PLAYER"|"SPECTATOR"};
type Public={phase:string;version:number;players:Player[];card?:{prompt:string};submittedCount:number;totalEligible:number;revealedVotes?:Record<string,{voter:string;target:string}>};
type Snapshot={room:{code:string;name:string};public:Public;private?:{submitted:boolean;allowedTargets:string[]}};
type Credential={playerId:string;token:string};
const key=(code:string)=>`rickie.credentials.${code}`;
const id=()=>crypto.randomUUID();

export function App(){
  const path=location.pathname.split("/").filter(Boolean); const shared=path[0]==="shared";
  const code=(shared?path[1]:path[0]==="room"?path[1]:undefined)?.toUpperCase();
  return shared&&code?<Game code={code} shared/>:code?<Join code={code}/>:<Home/>;
}
function Home(){
  const [roomName,setRoomName]=useState("Noite da galera"); const [nickname,setNickname]=useState(""); const [error,setError]=useState("");
  async function create(event:React.FormEvent){event.preventDefault();setError("");const response=await fetch(`${api}/api/rooms`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({roomName,hostNickname:nickname})});const data=await response.json();if(!response.ok)return setError(data.error??"Não foi possível criar a sala.");localStorage.setItem(key(data.code),JSON.stringify({playerId:data.playerId,token:data.token}));location.assign(`/room/${data.code}`);}
  return <main className="landing"><p className="eyebrow">JOGOS PARA A RODA</p><h1>Rickie <i>Games</i></h1><p className="lead">Celulares privados. Uma sala. Muitas histórias para lembrar.</p><form onSubmit={create} className="panel"><label>Nome da sala<input value={roomName} onChange={event=>setRoomName(event.target.value)} maxLength={40}/></label><label>Seu apelido<input value={nickname} onChange={event=>setNickname(event.target.value)} maxLength={18} required placeholder="Ex.: Duda"/></label><button>Criar sala</button>{error&&<p role="alert">{error}</p>}</form><small>Conteúdo demonstrativo original · 18+</small></main>;
}
function Join({code}:{code:string}){
  const [credential,setCredential]=useState<Credential|null>(()=>JSON.parse(localStorage.getItem(key(code))??"null"));const [nickname,setNickname]=useState("");const [room,setRoom]=useState<{name:string;phase:string}|null>(null);const [error,setError]=useState("");
  useEffect(()=>{fetch(`${api}/api/rooms/${code}`).then(response=>response.ok?response.json():Promise.reject()).then(setRoom).catch(()=>setError("Sala não encontrada ou encerrada."));},[code]);
  async function join(event:React.FormEvent){event.preventDefault();const response=await fetch(`${api}/api/rooms/${code}/join`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nickname,role:"PLAYER"})});const data=await response.json();if(!response.ok)return setError(data.error==="NICKNAME_TAKEN"?"Esse apelido já está na sala.":data.error??"Não foi possível entrar.");const next={playerId:data.playerId,token:data.token};localStorage.setItem(key(code),JSON.stringify(next));setCredential(next);}
  if(credential)return <Game code={code} credential={credential}/>;
  return <main className="landing"><p className="eyebrow">ENTRAR NA RODA</p><h1>{room?.name??"Carregando…"}</h1><form onSubmit={join} className="panel"><label>Seu apelido<input value={nickname} onChange={event=>setNickname(event.target.value)} minLength={2} maxLength={18} required autoFocus/></label><button>Entrar para jogar</button>{error&&<p role="alert">{error}</p>}</form></main>;
}
function Game({code,credential,shared=false}:{code:string;credential?:Credential;shared?:boolean}){
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [connected,setConnected]=useState(false);const [error,setError]=useState("");
  const socket=useMemo<Socket>(()=>io(api,{auth:{roomCode:code,playerId:credential?.playerId,token:credential?.token,shared},reconnection:true}),[code,credential?.playerId,credential?.token,shared]);
  useEffect(()=>{socket.on("connect",()=>setConnected(true));socket.on("disconnect",()=>setConnected(false));socket.on("connect_error",()=>setError("Não foi possível reconectar. Confira a sala."));socket.on("snapshot",setSnapshot);socket.on("public:update",(update:Pick<Snapshot,"room"|"public">)=>setSnapshot(old=>old?{...old,...update}:{...update}));socket.on("private:update",(privateView:Snapshot["private"])=>setSnapshot(old=>old?{...old,private:privateView}:old));return()=>{socket.close();};},[socket]);
  const send=(type:string,targetId?:string)=>socket.emit("command",{type,commandId:id(),expectedVersion:snapshot?.public.version??0,...(targetId?{targetId}:{})},(answer:{ok:boolean;error?:string})=>{if(!answer.ok)setError(answer.error??"Ação não permitida.");});
  if(!snapshot)return <main className="game"><p>Conectando à sala…</p></main>;
  const publicView=snapshot.public;const me=credential&&publicView.players.find(player=>player.id===credential.playerId);const isHost=me?.role==="HOST";
  return <main className={shared?"shared":"game"}><header><a href="/">Rickie Games</a><span className={connected?"online":"offline"}>{connected?"● ao vivo":"● reconectando"}</span></header><section className="room-head"><p className="eyebrow">{snapshot.room.name}</p><h2>{publicView.phase==="LOBBY"?"A roda está se formando":publicView.phase==="ROUND_RESULTS"?"Resultado!":publicView.card?.prompt??"Fim da demonstração"}</h2>{publicView.phase==="INPUT_OPEN"&&<p>{publicView.submittedCount}/{publicView.totalEligible} votos recebidos</p>}</section>{publicView.phase==="LOBBY"&&<Lobby code={code} shared={shared} isHost={isHost} onStart={()=>send("START")}/>} {!shared&&publicView.phase==="INPUT_OPEN"&&<Vote players={publicView.players} allowed={snapshot.private?.allowedTargets??[]} submitted={snapshot.private?.submitted??false} onVote={target=>send("VOTE",target)}/>} {publicView.phase==="ROUND_RESULTS"&&<Results publicView={publicView}/>} {isHost&&!shared&&publicView.phase==="INPUT_OPEN"&&<div className="host-actions"><button className="secondary" onClick={()=>send("CLOSE_VOTING")}>Encerrar votação</button><button className="secondary" onClick={()=>send("REMOVE_CARD")}>Remover carta</button></div>} {isHost&&!shared&&publicView.phase==="ROUND_RESULTS"&&<div className="host-actions"><button onClick={()=>send("NEXT_ROUND")}>Próxima rodada</button></div>} {publicView.phase==="FINISHED"&&<p className="finish">Fim da demonstração. Crie uma nova sala para recomeçar.</p>}<Scoreboard players={publicView.players}/>{error&&<p className="error" role="alert">{error}</p>}</main>;
}
function Lobby({code,shared,isHost,onStart}:{code:string;shared:boolean;isHost:boolean;onStart:()=>void}){const [qr,setQr]=useState("");const link=`${location.origin}/room/${code}`;useEffect(()=>{QRCode.toDataURL(link,{margin:1,width:220,color:{dark:"#10162f",light:"#fff6e9"}}).then(setQr);},[link]);return <section className="lobby">{!shared&&isHost&&<button onClick={onStart}>Começar demonstração</button>}<p>Entre pelo código <strong>{code}</strong></p>{(shared||isHost)&&<img className="qr" src={qr} alt={`QR code para entrar na sala ${code}`}/>}<p className="hint">A sala começa quando a pessoa anfitriã iniciar.</p></section>}
function Vote({players,allowed,submitted,onVote}:{players:Player[];allowed:string[];submitted:boolean;onVote:(id:string)=>void}){if(submitted)return <section className="panel centered"><h3>Voto protegido</h3><p>Seu voto foi registrado. Espere a revelação coletiva.</p></section>;return <section className="choices"><p>Seu voto é secreto até todo mundo votar.</p>{players.filter(player=>allowed.includes(player.id)).map(player=><button key={player.id} className="choice" onClick={()=>onVote(player.id)}>{player.nickname}</button>)}</section>}
function Results({publicView}:{publicView:Public}){return <section className="panel"><h3>Votos revelados simultaneamente</h3>{Object.entries(publicView.revealedVotes??{}).map(([id,vote])=><p key={id}><b>{vote.voter}</b> votou em <b>{vote.target}</b></p>)}</section>}
function Scoreboard({players}:{players:Player[]}){return <section className="scores"><h3>Placar</h3>{[...players].sort((a,b)=>b.score-a.score).map(player=><div key={player.id}><span>{player.nickname} {!player.connected&&"(ausente)"}</span><strong>{player.score}</strong></div>)}</section>}
